version: '3.9'

services:
  web:
    build: .
    container_name: django_app
    command: gunicorn --bind 0.0.0.0:8000 project_name.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=1
      - SECRET_KEY=d7ev6s*%xiq0*nh2#^%=!8-j+w&1u!s@vl%i$%3r%zhm8%lyo=
      - ALLOWED_HOSTS=127.0.0.1,localhost
      - DB_NAME=dbname
      - DB_USER=user
      - DB_PASSWORD=0000
      - DB_HOST=db
      - DB_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 0000
      POSTGRES_DB: dbname
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  celery:
    build: .
    container_name: celery_worker
    command: celery -A project_name worker --loglevel=info
    depends_on:
      - redis
      - db
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1

  celery_beat:
    build: .
    container_name: celery_beat
    command: celery -A project_name beat --loglevel=info
    depends_on:
      - redis
      - db
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1

volumes:
  postgres_data:
